name: Build And Deploy To Lambda

on:
  push:
    branches:
      - hoge
    #   - develop
    paths:
      - "lambda_handler/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Select branch to deploy"
        required: true
        default: "main"
        type: choice
        options:
          - main
          - experiment-edge

env:
  # lambda
  LAMBDA_FUNCTION_NAME: wr-${{ vars.ENV }}-wanrun-ssr

  # s3
  S3_BUCKET_NAME: wr-${{ vars.ENV }}-webapp
  
  # aws
  AWS_REGION: ap-northeast-1
  AWS_ROLE_ARN: arn:aws:iam::${{ vars.DEVELOP_AWS_ACCOUNT }}:role/github-actions

jobs:
  go-build:
    name: Lambda-build-and-deploy
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download server files from S3
        run: |
          # aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/server/ server/ --recursive
          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/standalone/ ./ --recursive
          aws s3 cp s3://${{ env.S3_BUCKET_NAME }}/static/ .next/ --recursive

      - name: Install Zip
        run: |
          sudo apt update
          sudo apt install -y zip

      - name: Create ZIP file
        run: |
          mv lambda_handler/index.js .
          ls -al
          zip -r lambda.zip index.js standalone/

      - name: setup-python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      # バージニア北部リージョン (us-east-1) の認証情報を設定
      - name: Configure AWS credentials for Virginia
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}          
          aws-region: us-east-1

      - name: Upload new Lambda version
        run: |
          # ZIP ファイルをアップロード
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip

          # 新しいバージョンを発行
          # VERSION=$(aws lambda publish-version --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --query Version --output text)
          
          # echo "New Lambda version: $VERSION"
